[package]
name = "tiny-rust-browser"
version = "0.1.0"
authors = ["VentGrey <omarpurataf@gmail.com>"]
edition = "2018"

[dependencies]
gfx = "0.17.1"
gfx_text = "0.23.0"
gfx_window_glutin = "0.28.0"
glutin = "0.19.0"