[package]
name = "tiny_rust_browser"
version = "0.1.0"
authors = ["VentGrey <omarpurataf@gmail.com>"]
edition = "2018"

[dependencies]
gfx = "0.14.1"
gfx_text = "0.15.0"
gfx_window_glutin = "0.14.0"
glutin = "0.22.0"

[[bin]]
name = "main"
path = "bin/main.rs"